### ISSUE TITLE
revise validation and publication workflow

### ISSUE THREAD

**Issue by chiarcos** [acoli-repo/olia#19]
- [x] create a central Makefile
- [x] automated XML, RDF and OWL validation (#5) 
  - [x] XML validation with xmllint (=> `make release`)
  - [x] RDF validation with rapper (=> `make release`)
  - [x] drop `tools/validate_with_bash.sh`
  - [x] drop `tools/validate_with_eyeball.sh` and `tools/eyeball` ([Eyeball is deprecated](https://jena.apache.org/documentation/archive/eyeball/eyeball-manual.html))
  - [x] integrate OWL validation with Pellet (=> `make validate`)
- [ ] automated validation of ontology metadata (#1)
  - [x] check `rdfs:label`s (#4)
- [x] copy valid ontologies (from `stable/`, `core/` and `experimental/`) to `docs/owl`
- [x] update Purl links to point to `https://acoli-repo.github.io/olia/owl` (cf. #10)
- [ ] automated generation/refresh of `docs/html`
  - [ ] update/replace/automatize `tools/olia2html`
- [ ] automated generation/update of `docs/models.md`
